# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6e9a097689a815b6ad2447e9bdb774de8d813c04abfe389139909ec06f2b8ba65a2bc2b60e0f5fd3d015234055de67727fc201e1f6edd2b1984b1faad7319c1

test:
  secret_key_base: ca2d8ffd595308c3c46ada0855e644ca7823d8d46c7527f265fab85d36e080e8cbb412aac58b9a14c6665fbcde432ce43a3bded6a5cbc6e8d05b0e8a8ce2e3bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
